name: Readable data changes

on: 
  pull_request:

jobs:
  readable-data-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          separator: "\n"
          old_new_files_separator: "\n"
          output_renamed_files_as_deleted_and_added: true
          include_all_old_new_renamed_files: true
          recover_deleted_files: true
            
      - name: Parse asset changes to be more readable
        id: readable-assets
        run: python readableAssets.py
        env:
          REPO: ${{ github.repository }}
          REPO_PATH: ${{ github.workspace }}
          PRNUM: ${{ github.event.number }}
          CHANGES_ALL: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          CHANGES_DELETED: ${{ steps.changed-files.outputs.deleted_files }}
          CHANGES_ADDED: ${{ steps.changed-files.outputs.added_files }}
          CHANGES_RENAME_PAIRS: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.readable-assets.outputs.OUTPUT_MESSAGE }}
